In [14]:
import pandas as pd

In [15]:
data = pd.read_csv("supervised_learning.csv")
data

       Age  Income Student Creditrating Buyscomputer
0    Youth    High      No         Fair           No
1    Youth    High      No    Excellent           No
2   Middle    High      No         Fair          Yes
3   Senior  Medium      No         Fair          Yes
4   Senior     Low     Yes         Fair          Yes
5   Middle     Low     Yes    Excellent           No
6   Senior     Low     Yes    Excellent          Yes
7    Youth  Medium      No         Fair           No
8    Youth     Low     Yes         Fair          Yes
9   Senior  Medium     Yes         Fair          Yes
10   Youth  Medium     Yes    Excellent          Yes
11  Middle  Medium      No    Excellent          Yes
12  Middle    High     Yes         Fair          Yes
13  Senior  Medium      No    Excellent           No

In [16]:
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]
X
Y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Buyscomputer, dtype: object

In [17]:
X['Age'] = X['Age'].map({'Youth': 1, 'Middle': 2, 'Senior': 3})
X['Income'] = X['Income'].map({'High': 1, 'Medium': 2, 'Low': 3})
X['Student'] = X['Student'].map({'No': 0, 'Yes': 1})
X['Creditrating'] = X['Creditrating'].map({'Fair': 0, 'Excellent': 1})
X

C:\Users\student\AppData\Local\Temp\ipykernel_6156\2651071965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age'] = X['Age'].map({'Youth': 1, 'Middle': 2, 'Senior': 3})
C:\Users\student\AppData\Local\Temp\ipykernel_6156\2651071965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Income'] = X['Income'].map({'High': 1, 'Medium': 2, 'Low': 3})
C:\Users\student\AppData\Local\Temp\ipykernel_6156\2651071965.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Student'] = X['Student'].map({'No': 0, 'Yes': 1})
C:\Users\student\AppData\Local\Temp\ipykernel_6156\2651071965.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Creditrating'] = X['Creditrating'].map({'Fair': 0, 'Excellent': 1})

    Age  Income  Student  Creditrating
0     1       1        0             0
1     1       1        0             1
2     2       1        0             0
3     3       2        0             0
4     3       3        1             0
5     2       3        1             1
6     3       3        1             1
7     1       2        0             0
8     1       3        1             0
9     3       2        1             0
10    1       2        1             1
11    2       2        0             1
12    2       1        1             0
13    3       2        0             1

In [18]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X,Y)
print(nb.predict([[3,3,1,1]]))
print(nb.predict([[1,1,0,0]]))
print(nb.predict([[1,1,1,1]]))

['Yes']
['No']
['Yes']

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(